### ISSUE TITLE
the installation is broken following the readme 

### ISSUE THREAD

**Issue by dmarcus-wire** [redhat-na-ssa/demo-ocp-gpt2-keras-nlp#2]
following the README steps 

# oc login to your cluster
$ git clone https://github.com/redhat-na-ssa/demo-ai-gitops-catalog.git ==PASS
$ cd demo-ai-gitops-catalog ==ADD STEP
$ bash ==PASS
$ source scripts/functions.sh  ==PASS
$ apply_firmly clusters/default/ ==PASS
$ git clone https://github.com/redhat-na-ssa/demo-ocp-gpt2-keras-nlp.git ==PASS
$ cd demo-ocp-gpt2-keras-nlp ==PASS
$ ./scripts/bootstrap.sh == FAILS

./scripts/bootstraps.sh
bash: ./scripts/bootstraps.sh: No such file or directory
bash-3.2$ ./scripts/bootstrap.sh
GIT_ROOT: /Users/abradhak/aimlprojects/demo-ai-gitops-catalog/demo-ocp-gpt2-keras-nlp
SCRIPT_DIR: /Users/abradhak/aimlprojects/demo-ai-gitops-catalog/demo-ocp-gpt2-keras-nlp/scripts
Kubernetes control plane is running at https://api.cluster-5lk2n.dynamic.opentlc.com:6443/
admin

Current OCP version: 4.14.2
Tested OCP version(s): 4.12.12 4.12.33 4.13.13

error: must build at directory:
error: must build at directory: not a valid directory: evalsymlink failure on 'components/operators/nfd/operator/overlays/stable' : lstat /Users/abradhak/aimlprojects/demo-ai-gitops-catalog/demo-ocp-gpt2-keras-nlp/components: no such file or directory

**Comment by codekow** [comment]
Addressed in refactor of repo
